PL/Controllers/EmpleadoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.Remoting.Metadata.W3cXsd2001;
using System.Web;
using System.Web.Mvc;

namespace PL.Controllers
{
    public class EmpleadoController : Controller
    {
       

        // GET: Empleado

        [HttpGet]
        public ActionResult Report()
        {
            int Year = 0;
            ML.Result result = BL.Empleado.GetReport(Year);
            
            ML.Result result1 = BL.Empleado.AnyosGet();
            
            ML.Orders orders = new ML.Orders();

            orders.Anyos = new ML.Anyo();
            orders.Anyos.Anyos = result1.Objects;

            orders.OrderS = result.Objects;

            

            return View(orders);
        }

        [HttpPost]
        public ActionResult Report(int? Year)
        {

            ML.Result result = BL.Empleado.GetReport(Year.Value);

            ML.Result result1 = BL.Empleado.AnyosGet();

            ML.Orders orders = new ML.Orders();

            orders.Anyos = new ML.Anyo();
            orders.Anyos.Anyos = result1.Objects;

            orders.OrderS = result.Objects;



            return View(orders);
        }


        public ActionResult Report3()
        {
            ML.Result result = BL.Empleado.GetAllTercer0();
            ML.Orders orders = new ML.Orders();
            orders.OrderS = result.Objects;
            return View(orders);
        }

        public ActionResult ReportDescontinuado()
        {
            ML.Result result = BL.Empleado.GetPrimero();
            ML.Products products = new ML.Products();
            products.ProductS = result.Objects;
            return View(products);
        }

        public ActionResult ReportPromedio()
        {
            ML.Result result = BL.Empleado.GetPromedio();
            ML.Products products = new ML.Products();

            products.ProductS = result.Objects;
            return View(products);
        }

    }
}

PL/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PL.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

PL/Views/Empleado/Report.cshtml
@model ML.Orders
@{
    ViewBag.Title = "Report";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Report</h2>


<br />

<div>
    @using (Html.BeginForm("Report", "Empleado", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {
        @*<div class="row">
            <div class="col-md-4">
                @Html.TextBoxFor(model => model.Year, new { @class = "form-control hiden" })
            </div>


            <div class="row">
                <div class="col-md-12">
                    @Html.LabelFor(model => model.Anyos)
                    @Html.DropDownListFor(model => model.Anyos.AnyO, new SelectList(Model.Anyos.Anyos), "Seleccione una opción")
                </div>
                @Html.HiddenFor(model => model.Anyos.Anyos)
            </div>*@

            <div class="row">
                <div class="col-md-12">
                    @Html.LabelFor(model => model.Year)
                    @Html.DropDownListFor(model => model.Year, new SelectList(Model.Anyos.Anyos), "Seleccione una opción")
                </div>
                @Html.HiddenFor(model => model.Year)
            </div>
        @*</div>*@

            <div class="col-md-4">
                <input type="submit" data-toggle="modal" class="btn btn-success" value="Buscar" />
            </div>

        @*</div>*@


            }
        </div>


<br />



@if (Model.OrderS != null)
{
    <div class="row table-responsive">
        <div class="col col-md-12">

            <table class="table table-bordered table-hover">

                <thead>
                    <tr>
                        <th>OrderDate</th>
                        <th>CompanyName</th>
                        <th>OrderID</th>
                        <th>Quantity</th>
                        <th>ProductName</th>
                        <th>CompanyNameSuppliers</th>
                        <th>City</th>

                    </tr>
                </thead>

                <tbody>
                    @foreach (ML.Orders order in Model.OrderS)
                    {
                        <tr>

                            <td>@order.OrderDate.ToString("dd/MM/yyyy")</td>
                            <td>@order.SupplierS.CompanyName</td>
                            <td>@order.OrderID</td>
                            <td>@order.DetailS.Quantity</td>
                            <td>@order.ProductS.ProductName</td>
                            <td>@order.SupplierS.CompanyName</td>
                            <td>@order.SupplierS.City</td>

                        </tr>



                    }
                </tbody>

            </table>

        </div>

    </div>
}

PL/Views/Empleado/Report3.cshtml
@model ML.Orders
@{
    ViewBag.Title = "Report3";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Report3</h2>

@if (Model.OrderS != null)
{
    <div class="row">
        <div class="col col-md-12">
            <div class="table table-responsive">
                <table class="table table-bordered">
                    <thead>
                        <tr>
                            <th>OrderDate</th>
                            <th>CompanyName</th>
                            <th>OrderID</th>
                            <th>Quantity</th>
                            <th>ProductName</th>
                            <th>CompanyNameSuppliers</th>
                            <th>City</th>
                        </tr>
                    </thead>

                    <tbody>
                        @foreach (ML.Orders order in Model.OrderS)
                        {

                            <tr>
                                <td>@order.OrderDate.ToString("dd/MM/yyyy")</td>
                                <td>@order.SupplierS.CompanyName</td>
                                <td>@order.OrderID</td>
                                <td>@order.DetailS.Quantity</td>
                                <td>@order.ProductS.ProductName</td>
                                <td>@order.SupplierS.CompanyName</td>
                                <td>@order.SupplierS.City</td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
}

PL/Views/Empleado/ReportDescontinuado.cshtml
@model ML.Products
@{
    ViewBag.Title = "ReportDescontinuado";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Descontinuado</h2>

@if (Model.ProductS != null)
{
    <div class="row">
        <div class="col col-md-12">
            <div class="table table-responsive">
                <table class="table table-bordered">
                    <thead>
                        <tr>
                            <th>ProductId</th>
                            <th>ProductName</th>
                            <th>Discontinued</th>
                            <th>SupplierId</th>
                            <th>UnitPrice</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (ML.Products products in Model.ProductS)
                        {
                            <tr>
                                <td>@products.ProductID</td>
                                <td>@products.ProductName</td>
                                <td>@products.Discontinued</td>
                                <td>@products.SupplierID</td>
                                <td>@products.UnitPrice</td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
}

PL/Views/Empleado/ReportPromedio.cshtml
@model ML.Products
@{
    ViewBag.Title = "ReportPromedio";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Promedio</h2>

@if (Model.ProductS != null)
{
    <div class="row">
        <div class="col col-md-12">
            <div class="table table-responsive">
                <table class="table table-bordered">
                    <thead>
                        <tr>
                            <th>ProductId</th>
                            <th>ProductName</th>
                            <th>CategoryId</th>
                            <th>CategoryName</th>
                            <th>UnitePrice</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (ML.Products products in Model.ProductS)
                        {
                            <tr>
                                <td>@products.ProductID</td>
                                <td>@products.ProductName</td>
                                <td>@products.CategorieS.CategoryID</td>
                                <td>@products.CategorieS.CategoryName</td>
                                <td>@products.UnitPrice</td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
}

PL/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<main aria-labelledby="title">
    <h2 id="title">@ViewBag.Title.</h2>
    <h3>@ViewBag.Message</h3>

    <p>Use this area to provide additional information.</p>
</main>

PL/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<main aria-labelledby="title">
    <h2 id="title">@ViewBag.Title.</h2>
    <h3>@ViewBag.Message</h3>

    <address>
        One Microsoft Way<br />
        Redmond, WA 98052-6399<br />
        <abbr title="Phone">P:</abbr>
        425.555.0100
    </address>

    <address>
        <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
        <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
    </address>
</main>

PL/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<main>
    <section class="row" aria-labelledby="aspnetTitle">
        <h1 id="title">ASP.NET</h1>
        <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
        <p><a href="https://asp.net" class="btn btn-primary btn-md">Learn more &raquo;</a></p>
    </section>

    <div class="row">
        <section class="col-md-4" aria-labelledby="gettingStartedTitle">
            <h2 id="gettingStartedTitle">Getting started</h2>
            <p>
                ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
                enables a clean separation of concerns and gives you full control over markup
                for enjoyable, agile development.
            </p>
            <p><a class="btn btn-outline-dark" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
        </section>
        <section class="col-md-4" aria-labelledby="librariesTitle">
            <h2 id="librariesTitle">Get more libraries</h2>
            <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
            <p><a class="btn btn-outline-dark" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
        </section>
        <section class="col-md-4" aria-labelledby="hostingTitle">
            <h2 id="hostingTitle">Web Hosting</h2>
            <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
            <p><a class="btn btn-outline-dark" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
        </section>
    </div>
</main>

PL/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Mi aplicación ASP.NET</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark">
        <div class="container">
            @Html.ActionLink("Sanborns", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" title="Alternar navegación" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li>@Html.ActionLink("Inicio", "Index", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Acerca de", "About", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Contacto", "Contact", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Buequeda", "Report", "Empleado", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Reporte", "Report3", "Empleado", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Descontinuado", "ReportDescontinuado", "Empleado", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Promedio", "ReportPromedio", "Empleado", new { area = "" }, new { @class = "nav-link" })</li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Mi aplicación ASP.NET</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>